/// <reference types='cypress'/>

describe('OpenSourceBilling',function()
{
    it('OSB',function()
    {
        cy.visit('http://demo.opensourcebilling.org/')
        cy.get('#email').clear().type('demo@opensourcebilling.org')
        cy.get('#password').clear().type('password')
        cy.get('#user_login_btn').click()
        //cy.get('.introjs-skipbutton').click()
        cy.get('[title="Items"]').click()
        //cy.get('.introjs-skipbutton').click()
        cy.get('.primary_new_link').click()
        //cy.get('.introjs-skipbutton').click()
        cy.get('#item_item_name').type('Test2022')
        cy.get('#item_item_description').type('for testing purpose')
        cy.get('#item_unit_cost').type('150')
        cy.get('#item_quantity').type('1000')
        cy.get('#select2-chosen-5').click()
        cy.get('#select2-results-5').contains('CGST').click()
        //cy.get('#select2-result-label-56').click()
        //cy.get('#select2-chosen-5').click({force:true}).type('{enter}')
       // cy.get('#item_tax_2').select('29').should('have.value','CGST')
        cy.get('#company_association').click({force:true})
        cy.get('#company_1').click({force:true})
        cy.get('#company_2').check({force:true})
        cy.get('[title=Save]').click()
    })
})